//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashDouble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int BookingID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Model Model { get; set; }
        public virtual Photographer Photographer { get; set; }
    }
}
